#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

GO(jack_free, vFp)
GOM(jack_on_shutdown, vFEppp)
GO(jack_port_name, pFp)
GO(jack_connect, iFppp)
GOM(jack_set_process_callback, iFEppp)
GOM(jack_set_buffer_size_callback, iFEppp)
GO(jack_port_register, pFpppLL)
GO(jack_midi_event_get, iFppu)
GO(jack_port_get_buffer, pFpu)
GO(jack_get_ports, pFpppL)
GO(jack_midi_get_event_count, uFp)
GOM(jack_set_port_registration_callback, iFEppp)
GO(jack_get_sample_rate, uFp)
GOM(jack_set_sample_rate_callback, iFEppp)
GO(jack_client_close, iFp)
GOM(jack_client_open, pFpip)
GO(jack_activate, iFp)
